version: '3.9'
services:

  mongo:
    image: mongo
    restart: always
    ports:
      - '6379:6379'

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - mysql
      - redis

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - mongo
      - api

volumes:
  mysql-data: